import { randomUUID } from "node:crypto";
import { and, eq, gte, isNotNull } from "drizzle-orm";
import { getEnv } from "@/config/env";
import { getDb } from "@/db/client";
import { auditLog, pendingInboundEmails } from "@/db/schema";
import { detectAutoGeneratedSignal, ownDomainsFromEnv } from "@/email/auto-reply";
import { buildUnknownSenderReply } from "@/email/inbound";
import type { NormalizedEmail } from "@/email/normalize";
import type { EmailSender, OutboundEmailStore } from "@/email/outbound";
import { getEmailSender } from "@/email/sender-factory";
import { sendSystemEmail } from "@/email/system-send";
import { inngest } from "@/workflows/client";

// ---------------------------------------------------------------------------
// Ports — pure interfaces so tests can inject in-memory fakes
// ---------------------------------------------------------------------------

export type PendingRow = {
  id: string;
  senderEmail: string;
  activationSentAt: Date | null;
  normalizedPayload: NormalizedEmail;
};

export interface ActivationRepository {
  /**
   * Load the pending_inbound_emails row by its primary key.
   * Returns null when the row does not exist or has already been claimed.
   */
  findPendingById(id: string): Promise<PendingRow | null>;

  /**
   * Returns true when ANY pending_inbound_emails row for `senderEmail` has an
   * `activation_sent_at` value that is after `windowStart`.
   */
  hasRecentActivation(senderEmail: string, windowStart: Date): Promise<boolean>;

  /**
   * Stamp `activation_sent_at` on the given row.
   */
  stampActivationSentAt(id: string, sentAt: Date): Promise<void>;

  /**
   * Write an audit log row.
   */
  writeAudit(input: {
    action: "email.activation_sent" | "email.activation_suppressed";
    metadata: Record<string, unknown>;
  }): Promise<void>;
}

// ---------------------------------------------------------------------------
// Result shapes for each phase
// ---------------------------------------------------------------------------

export type SuppressedResult =
  | { status: "missing_pending" }
  | { status: "suppressed_auto_generated"; signal: string }
  | { status: "suppressed_recent_activation" }
  | { status: "suppressed_already_stamped" };

export type ActivationCheckResult =
  | SuppressedResult
  | { status: "clear"; senderEmail: string };

export type ActivationResult =
  | SuppressedResult
  | { status: "sent"; providerMessageId: string };

// ---------------------------------------------------------------------------
// Phase A: check — load, auto-generated detection, suppression window
// ---------------------------------------------------------------------------

/**
 * Pure check function. Inspects the pending row and returns either a suppression
 * reason or `{ status: "clear" }` with the sender email ready for the send step.
 *
 * `now` must be injected from inside an Inngest step so it is memoized and
 * stable across Inngest's per-step re-executions (per the canary lesson).
 */
export async function checkActivation(
  pendingInboundEmailId: string,
  options: {
    repository: ActivationRepository;
    /** Own domains for auto-generated detection; derived from env when omitted. */
    ownDomains?: string[];
    /** Current timestamp — MUST come from inside a step.run. */
    now: Date;
  },
): Promise<ActivationCheckResult> {
  const row = await options.repository.findPendingById(pendingInboundEmailId);

  if (!row) {
    return { status: "missing_pending" };
  }

  // Belt to Inngest-level idempotency: suppress if already stamped.
  if (row.activationSentAt !== null) {
    return { status: "suppressed_already_stamped" };
  }

  const ownDomains = options.ownDomains ?? ownDomainsFromEnv();
  const autoSignal = detectAutoGeneratedSignal(row.normalizedPayload, ownDomains);

  if (autoSignal !== null) {
    await options.repository.writeAudit({
      action: "email.activation_suppressed",
      metadata: {
        pendingInboundEmailId,
        senderEmail: row.senderEmail,
        reason: "auto_generated",
        signal: autoSignal,
      },
    });
    return { status: "suppressed_auto_generated", signal: autoSignal };
  }

  const windowStart = new Date(options.now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const recentlySent = await options.repository.hasRecentActivation(row.senderEmail, windowStart);

  if (recentlySent) {
    await options.repository.writeAudit({
      action: "email.activation_suppressed",
      metadata: {
        pendingInboundEmailId,
        senderEmail: row.senderEmail,
        reason: "recent_activation",
      },
    });
    return { status: "suppressed_recent_activation" };
  }

  return { status: "clear", senderEmail: row.senderEmail };
}

// ---------------------------------------------------------------------------
// Phase B: send-only — build reply and deliver; NO DB writes
// ---------------------------------------------------------------------------

/**
 * Sends the activation email and returns the provider message ID.
 * Deliberately performs NO database writes so that a Postmark-accepted send
 * that is followed by a failed DB write does not cause a double-send on retry.
 *
 * `now` must be injected from inside an Inngest step so it is memoized.
 */
export async function sendActivationEmailOnly(
  senderEmail: string,
  options: {
    sender: EmailSender;
    store?: OutboundEmailStore;
    appUrl: string;
    /** Current timestamp — MUST come from inside a step.run. */
    now: Date;
  },
): Promise<{ providerMessageId: string }> {
  const reply = buildUnknownSenderReply(senderEmail, options.appUrl);

  const { providerMessageId } = await sendSystemEmail({
    email: {
      to: reply.to,
      subject: reply.subject,
      textBody: reply.text,
    },
    sender: options.sender,
    store: options.store,
    now: () => options.now,
  });

  return { providerMessageId };
}

// ---------------------------------------------------------------------------
// Phase C: record — stamp + audit after a confirmed send
// ---------------------------------------------------------------------------

/**
 * Stamps `activation_sent_at` and writes the `email.activation_sent` audit row.
 * Called only after `sendActivationEmailOnly` has successfully returned a
 * `providerMessageId`, so a retry here never re-sends the email.
 *
 * `now` must be injected from inside an Inngest step (separate from the send
 * step) so it is independently memoized.
 */
export async function recordActivationSent(
  pendingInboundEmailId: string,
  senderEmail: string,
  providerMessageId: string,
  options: {
    repository: ActivationRepository;
    /** Current timestamp — MUST come from inside a step.run. */
    now: Date;
  },
): Promise<void> {
  await options.repository.stampActivationSentAt(pendingInboundEmailId, options.now);

  await options.repository.writeAudit({
    action: "email.activation_sent",
    metadata: {
      pendingInboundEmailId,
      senderEmail,
      providerMessageId,
    },
  });
}

// ---------------------------------------------------------------------------
// Convenience combined function (used directly in tests via ports)
// ---------------------------------------------------------------------------

/**
 * Full activation flow: check → send → record. Designed for direct use in
 * tests with injected fakes. The Inngest wrapper splits this into three steps
 * for retry safety; this function composes the same split pieces in order.
 */
export async function sendActivationEmail(
  pendingInboundEmailId: string,
  options: {
    repository: ActivationRepository;
    sender: EmailSender;
    store?: OutboundEmailStore;
    ownDomains?: string[];
    appUrl: string;
    now: Date;
  },
): Promise<ActivationResult> {
  const checkResult = await checkActivation(pendingInboundEmailId, {
    repository: options.repository,
    ownDomains: options.ownDomains,
    now: options.now,
  });

  if (checkResult.status !== "clear") {
    return checkResult;
  }

  const { providerMessageId } = await sendActivationEmailOnly(checkResult.senderEmail, {
    sender: options.sender,
    store: options.store,
    appUrl: options.appUrl,
    now: options.now,
  });

  await recordActivationSent(pendingInboundEmailId, checkResult.senderEmail, providerMessageId, {
    repository: options.repository,
    now: options.now,
  });

  return { status: "sent", providerMessageId };
}


// ---------------------------------------------------------------------------
// Drizzle-backed repository implementation
// ---------------------------------------------------------------------------

export class DrizzleActivationRepository implements ActivationRepository {
  private readonly db = getDb();

  async findPendingById(id: string): Promise<PendingRow | null> {
    const [row] = await this.db
      .select({
        id: pendingInboundEmails.id,
        senderEmail: pendingInboundEmails.senderEmail,
        activationSentAt: pendingInboundEmails.activationSentAt,
        normalizedPayload: pendingInboundEmails.normalizedPayload,
        status: pendingInboundEmails.status,
      })
      .from(pendingInboundEmails)
      .where(eq(pendingInboundEmails.id, id))
      .limit(1);

    if (!row) {
      return null;
    }

    // Treat claimed rows as missing: their activation window is handled by
    // the sender_verified path, not here.
    if (row.status === "claimed") {
      return null;
    }

    return {
      id: row.id,
      senderEmail: row.senderEmail,
      activationSentAt: row.activationSentAt,
      normalizedPayload: row.normalizedPayload as NormalizedEmail,
    };
  }

  async hasRecentActivation(senderEmail: string, windowStart: Date): Promise<boolean> {
    const [row] = await this.db
      .select({ id: pendingInboundEmails.id })
      .from(pendingInboundEmails)
      .where(
        and(
          eq(pendingInboundEmails.senderEmail, senderEmail),
          isNotNull(pendingInboundEmails.activationSentAt),
          gte(pendingInboundEmails.activationSentAt, windowStart),
        ),
      )
      .limit(1);

    return row !== undefined;
  }

  async stampActivationSentAt(id: string, sentAt: Date): Promise<void> {
    await this.db
      .update(pendingInboundEmails)
      .set({ activationSentAt: sentAt, updatedAt: new Date() })
      .where(eq(pendingInboundEmails.id, id));
  }

  async writeAudit(input: {
    action: "email.activation_sent" | "email.activation_suppressed";
    metadata: Record<string, unknown>;
  }): Promise<void> {
    await this.db.insert(auditLog).values({
      id: randomUUID(),
      action: input.action,
      actorType: "system",
      metadata: input.metadata,
    });
  }
}

// ---------------------------------------------------------------------------
// Inngest wrapper — thin binding of Drizzle ports to the pure core
// ---------------------------------------------------------------------------

export const sendActivationEmailFunction = inngest.createFunction(
  {
    id: "send-activation-email",
    triggers: { event: "email.sender_unknown" },
    idempotency: "event.data.pendingInboundEmailId",
  },
  async ({ event, step }) => {
    const pendingInboundEmailId = event.data.pendingInboundEmailId as string;

    // Step (a+b): check — auto-generated detection + 7-day suppression window.
    // `now` is minted inside this step so it is memoized across re-executions.
    const checkResult = await step.run("check-activation", async () => {
      const now = new Date();
      return checkActivation(pendingInboundEmailId, {
        repository: new DrizzleActivationRepository(),
        now,
      });
    });

    if (checkResult.status !== "clear") {
      return { ok: true, ...checkResult };
    }

    // Step (b): send-only — Postmark call with NO DB writes. If this step
    // succeeds and the next step fails, Inngest retries "record-activation-sent"
    // without re-sending the email (providerMessageId is memoized).
    const sendResult = await step.run("send-activation-email", async () => {
      const now = new Date();
      const env = getEnv();
      return sendActivationEmailOnly(checkResult.senderEmail, {
        sender: getEmailSender(),
        appUrl: env.NEXT_PUBLIC_APP_URL,
        now,
      });
    });

    // Step (c): stamp + audit — isolated so a DB failure here retries without
    // re-sending. `now` is minted fresh inside this step and is independently
    // memoized by Inngest.
    await step.run("record-activation-sent", async () => {
      const now = new Date();
      await recordActivationSent(
        pendingInboundEmailId,
        checkResult.senderEmail,
        sendResult.providerMessageId,
        {
          repository: new DrizzleActivationRepository(),
          now,
        },
      );
    });

    return { ok: true, status: "sent", ...sendResult };
  },
);
