import type { NormalizedEmail } from "@/email/normalize";
import { getOptionalEnv } from "@/config/env";

/**
 * Returns the name of the first auto-generated signal that fired, or null if
 * the email looks human. Covers RFC-3834 and common mail-client headers.
 *
 * @param email      - Normalized inbound email (headers already lower-cased).
 * @param ownDomains - List of domain strings (e.g. ["keeps.ai", "keeps.email"])
 *                     that belong to our own sending / reply infrastructure.
 *                     A From address matching any of these domains is treated as
 *                     a self-loop and therefore auto-generated.
 */
export function detectAutoGeneratedSignal(
  email: NormalizedEmail,
  ownDomains: string[],
): string | null {
  const { headers, from } = email;

  // 1. Auto-Submitted header present and not "no"
  const autoSubmitted = headers["auto-submitted"];
  if (autoSubmitted !== undefined && autoSubmitted.toLowerCase().trim() !== "no") {
    return "auto-submitted";
  }

  // 2. Precedence: bulk | junk | list | auto_reply
  const precedence = headers["precedence"];
  if (precedence !== undefined) {
    const p = precedence.toLowerCase().trim();
    if (p === "bulk" || p === "junk" || p === "list" || p === "auto_reply") {
      return `precedence:${p}`;
    }
  }

  // 3. X-Auto-Response-Suppress present (Outlook OOO / auto-reply signal)
  if ("x-auto-response-suppress" in headers) {
    return "x-auto-response-suppress";
  }

  // 4. From address domain matches one of our own sending/reply domains
  const fromDomain = from.email.split("@")[1];
  if (fromDomain !== undefined) {
    const lowerFromDomain = fromDomain.toLowerCase();
    for (const domain of ownDomains) {
      if (domain.toLowerCase() === lowerFromDomain) {
        return `own-domain:${lowerFromDomain}`;
      }
    }
  }

  return null;
}

/**
 * RFC-3834-style auto-generated email detection.
 *
 * Returns true when the email was generated automatically (vacation responder,
 * OOO, mailing list, delivery notification, self-loop from our own sending
 * infrastructure) and should NOT be processed as a human capture request.
 *
 * Thin wrapper over detectAutoGeneratedSignal — stable exported signature.
 *
 * @param email      - Normalized inbound email (headers already lower-cased).
 * @param ownDomains - List of domain strings (e.g. ["keeps.ai", "keeps.email"])
 *                     that belong to our own sending / reply infrastructure.
 *                     A From address matching any of these domains is treated as
 *                     a self-loop and therefore auto-generated.
 */
export function isAutoGenerated(
  email: NormalizedEmail,
  ownDomains: string[],
): boolean {
  return detectAutoGeneratedSignal(email, ownDomains) !== null;
}

/**
 * Convenience wrapper that derives own-domains from environment config.
 *
 * Extracts the domain portion of POSTMARK_FROM_ADDRESS and
 * POSTMARK_REPLY_TO_BASE, deduplicates them, and calls isAutoGenerated.
 */
export function isAutoGeneratedEmail(email: NormalizedEmail): boolean {
  return isAutoGenerated(email, ownDomainsFromEnv());
}

/**
 * Extract unique domains from a list of email address strings.
 * Ignores entries that do not contain "@".
 */
function deriveDomains(addresses: string[]): string[] {
  const seen = new Set<string>();
  for (const addr of addresses) {
    const atIdx = addr.indexOf("@");
    if (atIdx !== -1) {
      seen.add(addr.slice(atIdx + 1).toLowerCase());
    }
  }
  return [...seen];
}

/**
 * Derives own domains from environment config (POSTMARK_FROM_ADDRESS and
 * POSTMARK_REPLY_TO_BASE). Exported so callers outside this module don't need
 * to duplicate the derivation logic.
 */
export function ownDomainsFromEnv(): string[] {
  const env = getOptionalEnv();
  return deriveDomains([env.POSTMARK_FROM_ADDRESS, env.POSTMARK_REPLY_TO_BASE]);
}
