import { describe, expect, it } from "vitest";
import { isAutoGenerated } from "@/email/auto-reply";
import { normalizePostmarkInbound } from "@/email/normalize";
import { directPostmarkFixture } from "@/email/fixtures/postmark";
import type { PostmarkInboundPayload } from "@/email/normalize";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a minimal Postmark payload by layering overrides on top of the
 *  standard directPostmarkFixture (a normal human email). */
function makePayload(overrides: Partial<PostmarkInboundPayload>): PostmarkInboundPayload {
  return {
    ...directPostmarkFixture,
    ...overrides,
    // Allow callers to append extra headers on top of the default set
    Headers: [
      ...(overrides.Headers ?? directPostmarkFixture.Headers),
    ],
  };
}

/** Normalize a payload and run isAutoGenerated with the provided own domains. */
function check(payload: PostmarkInboundPayload, ownDomains: string[] = []): boolean {
  return isAutoGenerated(normalizePostmarkInbound(payload), ownDomains);
}

// ---------------------------------------------------------------------------
// Header normalization — verify the three signal headers survive intact
// ---------------------------------------------------------------------------

describe("normalizePostmarkInbound header lowercasing", () => {
  it("lowercases Auto-Submitted into headers record", () => {
    const payload = makePayload({
      Headers: [{ Name: "Auto-Submitted", Value: "auto-replied" }],
    });
    const normalized = normalizePostmarkInbound(payload);
    expect(normalized.headers["auto-submitted"]).toBe("auto-replied");
  });

  it("lowercases Precedence into headers record", () => {
    const payload = makePayload({
      Headers: [{ Name: "Precedence", Value: "bulk" }],
    });
    const normalized = normalizePostmarkInbound(payload);
    expect(normalized.headers["precedence"]).toBe("bulk");
  });

  it("lowercases X-Auto-Response-Suppress into headers record", () => {
    const payload = makePayload({
      Headers: [{ Name: "X-Auto-Response-Suppress", Value: "OOF, AutoReply" }],
    });
    const normalized = normalizePostmarkInbound(payload);
    expect(normalized.headers["x-auto-response-suppress"]).toBe("OOF, AutoReply");
  });
});

// ---------------------------------------------------------------------------
// Positive cases — should return true
// ---------------------------------------------------------------------------

describe("isAutoGenerated – auto-generated emails", () => {
  it("returns true for a Gmail vacation responder (Auto-Submitted + Precedence bulk)", () => {
    const payload = makePayload({
      MessageID: "auto-gmail-vacation-001",
      From: "Arav (Automatic Reply) <arav@example.com>",
      FromFull: { Email: "arav@example.com", Name: "Arav (Automatic Reply)", MailboxHash: "" },
      Subject: "Auto: Out of office",
      TextBody: "I am away and will respond when I return.",
      Headers: [
        { Name: "Message-ID", Value: "<gmail-vacation-001@example.com>" },
        { Name: "Auto-Submitted", Value: "auto-replied" },
        { Name: "Precedence", Value: "bulk" },
      ],
    });

    expect(check(payload)).toBe(true);
  });

  it("returns true for an Outlook OOO email (X-Auto-Response-Suppress present)", () => {
    const payload = makePayload({
      MessageID: "auto-outlook-ooo-001",
      From: "Jordan <jordan@corp.com>",
      FromFull: { Email: "jordan@corp.com", Name: "Jordan", MailboxHash: "" },
      Subject: "Out of Office: Re: Partner renewal",
      TextBody: "I am out of office until Monday.",
      Headers: [
        { Name: "Message-ID", Value: "<outlook-ooo-001@corp.com>" },
        { Name: "X-Auto-Response-Suppress", Value: "OOF, AutoReply" },
      ],
    });

    expect(check(payload)).toBe(true);
  });

  it("returns true for a mailing list email (Precedence: list)", () => {
    const payload = makePayload({
      MessageID: "auto-mailinglist-001",
      From: "Keeps Digest <digest@list.example.com>",
      FromFull: { Email: "digest@list.example.com", Name: "Keeps Digest", MailboxHash: "" },
      Subject: "Weekly digest",
      TextBody: "Here is your weekly digest.",
      Headers: [
        { Name: "Message-ID", Value: "<mailinglist-001@list.example.com>" },
        { Name: "Precedence", Value: "list" },
      ],
    });

    expect(check(payload)).toBe(true);
  });

  it("returns true for a self-loop from our own domain (keeps.email)", () => {
    const payload = makePayload({
      MessageID: "auto-self-loop-001",
      From: "Keeps Agent <agent@keeps.email>",
      FromFull: { Email: "agent@keeps.email", Name: "Keeps Agent", MailboxHash: "" },
      Subject: "Nudge: your open loop",
      TextBody: "Just a reminder about your open loop.",
      Headers: [
        { Name: "Message-ID", Value: "<self-loop-001@keeps.email>" },
      ],
    });

    expect(check(payload, ["keeps.email"])).toBe(true);
  });

  it("returns true when Auto-Submitted is 'auto-generated'", () => {
    const payload = makePayload({
      MessageID: "auto-submitted-auto-generated-001",
      Headers: [
        { Name: "Message-ID", Value: "<ag-001@example.com>" },
        { Name: "Auto-Submitted", Value: "auto-generated" },
      ],
    });

    expect(check(payload)).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Negative cases — should return false
// ---------------------------------------------------------------------------

describe("isAutoGenerated – normal human emails", () => {
  it("returns false for a plain human email with no auto-generated signals", () => {
    // directPostmarkFixture is a plain human email with only a Message-ID header
    expect(check(directPostmarkFixture)).toBe(false);
  });

  it("returns false when Auto-Submitted is 'no'", () => {
    const payload = makePayload({
      MessageID: "auto-submitted-no-001",
      Headers: [
        { Name: "Message-ID", Value: "<no-001@example.com>" },
        { Name: "Auto-Submitted", Value: "no" },
      ],
    });

    expect(check(payload)).toBe(false);
  });

  it("returns false when Auto-Submitted is 'No' (case-insensitive)", () => {
    const payload = makePayload({
      MessageID: "auto-submitted-No-001",
      Headers: [
        { Name: "Message-ID", Value: "<no-002@example.com>" },
        { Name: "Auto-Submitted", Value: "No" },
      ],
    });

    expect(check(payload)).toBe(false);
  });

  it("returns false when the From domain matches a different own domain list", () => {
    // From is example.com but own domains list only has keeps.ai — no match
    expect(check(directPostmarkFixture, ["keeps.ai"])).toBe(false);
  });
});
